meta_product_name: "FoodieFeed"
meta_title: "FoodieFeed - Keep it groovy. Feed your Foodie"
meta_description: "A recipe platform to learn & expand your culinary horizon"
meta_image: "cover.png"
twitter_account: "@product_twitter_account"
